# Generated by Django 3.2.3 on 2021-06-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_item_img_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='links',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
