# Generated by Django 3.2.3 on 2021-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_item_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=500)),
                ('image2', models.CharField(max_length=500)),
                ('image3', models.CharField(max_length=500)),
                ('image4', models.CharField(max_length=500)),
                ('image5', models.CharField(max_length=500)),
                ('image6', models.CharField(max_length=500)),
                ('image7', models.CharField(max_length=500)),
                ('image8', models.CharField(max_length=500)),
                ('image9', models.CharField(max_length=500)),
                ('image10', models.CharField(max_length=500)),
                ('image11', models.CharField(max_length=500)),
                ('image12', models.CharField(max_length=500)),
                ('image13', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='links',
        ),
    ]
