# Generated by Django 3.2.3 on 2021-06-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20210614_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
