# Generated by Django 3.2.3 on 2021-06-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_images_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image9',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
