# Generated by Django 3.2.3 on 2021-06-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20210614_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='is_active',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
