# Generated by Django 3.2.3 on 2021-06-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_item_lamoda_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
