# Generated by Django 3.2.3 on 2021-06-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='count',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='market.item'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
