# Generated by Django 3.2.3 on 2021-06-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20210622_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='count',
            new_name='item',
        ),
    ]
