# Generated by Django 3.2.3 on 2021-06-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_rename_count_images_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='item',
            new_name='count',
        ),
    ]
