# Generated by Django 3.2.3 on 2021-06-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_rename_item_images_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='count',
            new_name='item',
        ),
    ]
