# Generated by Django 3.2.3 on 2021-06-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_rename_count_images_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='item',
        ),
        migrations.AddField(
            model_name='images',
            name='count',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
