# Generated by Django 3.2.3 on 2021-06-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210616_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
    ]
