# Generated by Django 3.2.3 on 2021-06-20 18:50

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_username_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=phone_field.models.PhoneField(blank=True, help_text='Телефон', max_length=31),
        ),
    ]
