# Generated by Django 3.2.3 on 2021-06-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
    ]
